'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Alignment Sheets\11x17 alignment sheet.pdf")>  _
        Public Property alignSheet11x17() As String
            Get
                Return CType(Me("alignSheet11x17"),String)
            End Get
            Set
                Me("alignSheet11x17") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Alignment Sheets\12x18 Alignment Sheet.pdf")>  _
        Public Property alignSheet12x18() As String
            Get
                Return CType(Me("alignSheet12x18"),String)
            End Get
            Set
                Me("alignSheet12x18") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Computer\BTP Programs\LineUp\Resources\")>  _
        Public Property dirResources() As String
            Get
                Return CType(Me("dirResources"),String)
            End Get
            Set
                Me("dirResources") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Bodies\4up 2cut\")>  _
        Public Property dirBkBod() As String
            Get
                Return CType(Me("dirBkBod"),String)
            End Get
            Set
                Me("dirBkBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Bodies\4up 3cut Full Bleed\")>  _
        Public Property dirBkBodBleed() As String
            Get
                Return CType(Me("dirBkBodBleed"),String)
            End Get
            Set
                Me("dirBkBodBleed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Covers\2up 12x18\")>  _
        Public Property dirBkCov() As String
            Get
                Return CType(Me("dirBkCov"),String)
            End Get
            Set
                Me("dirBkCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Brochures\")>  _
        Public Property dirBrochure() As String
            Get
                Return CType(Me("dirBrochure"),String)
            End Get
            Set
                Me("dirBrochure") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Charts\")>  _
        Public Property dirChart() As String
            Get
                Return CType(Me("dirChart"),String)
            End Get
            Set
                Me("dirChart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Leaflets\")>  _
        Public Property dirLeaflet() As String
            Get
                Return CType(Me("dirLeaflet"),String)
            End Get
            Set
                Me("dirLeaflet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Pamphlets\Bodies\Mini-Pamphlet\")>  _
        Public Property dirMiniPamBod() As String
            Get
                Return CType(Me("dirMiniPamBod"),String)
            End Get
            Set
                Me("dirMiniPamBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Pamphlets\Covers\Mini-Pamphlet\")>  _
        Public Property dirMiniPamCov() As String
            Get
                Return CType(Me("dirMiniPamCov"),String)
            End Get
            Set
                Me("dirMiniPamCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Pamphlets\Bodies\Pamphlet\")>  _
        Public Property dirPamBod() As String
            Get
                Return CType(Me("dirPamBod"),String)
            End Get
            Set
                Me("dirPamBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Pamphlets\Covers\Pamphlet\")>  _
        Public Property dirPamCov() As String
            Get
                Return CType(Me("dirPamCov"),String)
            End Get
            Set
                Me("dirPamCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Web\Products\3 Product Pics Master\")>  _
        Public Property dirWebProd() As String
            Get
                Return CType(Me("dirWebProd"),String)
            End Get
            Set
                Me("dirWebProd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Hymnbooks\Bodies\")>  _
        Public Property dirHymnbookBod() As String
            Get
                Return CType(Me("dirHymnbookBod"),String)
            End Get
            Set
                Me("dirHymnbookBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Hymnbooks\Covers\")>  _
        Public Property dirHymnbookCov() As String
            Get
                Return CType(Me("dirHymnbookCov"),String)
            End Get
            Set
                Me("dirHymnbookCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Tracts\Tract Cards\")>  _
        Public Property dirTractCard() As String
            Get
                Return CType(Me("dirTractCard"),String)
            End Get
            Set
                Me("dirTractCard") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\CDs\Album Covers\2up on 11x17\")>  _
        Public Property dirCdAlbumCov() As String
            Get
                Return CType(Me("dirCdAlbumCov"),String)
            End Get
            Set
                Me("dirCdAlbumCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Bodies\4up 2cut - 12x18")>  _
        Public Property dirBkBod12x9() As String
            Get
                Return CType(Me("dirBkBod12x9"),String)
            End Get
            Set
                Me("dirBkBod12x9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Covers\1up 12x18")>  _
        Public Property dirBkCov12x9() As String
            Get
                Return CType(Me("dirBkCov12x9"),String)
            End Get
            Set
                Me("dirBkCov12x9") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Books\Covers\4up 12x18 - Economy")>  _
        Public Property dirMiniEconBkCov() As String
            Get
                Return CType(Me("dirMiniEconBkCov"),String)
            End Get
            Set
                Me("dirMiniEconBkCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Books\Bodies\8up - MiniBook Economy")>  _
        Public Property dirMiniEconBkBod() As String
            Get
                Return CType(Me("dirMiniEconBkBod"),String)
            End Get
            Set
                Me("dirMiniEconBkBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property eServer() As String
            Get
                Return CType(Me("eServer"),String)
            End Get
            Set
                Me("eServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ePort() As String
            Get
                Return CType(Me("ePort"),String)
            End Get
            Set
                Me("ePort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ePassword() As String
            Get
                Return CType(Me("ePassword"),String)
            End Get
            Set
                Me("ePassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("btporders@bibletruthpublishers.com")>  _
        Public Property eSendAsUser() As String
            Get
                Return CType(Me("eSendAsUser"),String)
            End Get
            Set
                Me("eSendAsUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("btporders@bibletruthpublishers.com"& _ 
            "")>  _
        Public Property eMailTo() As String
            Get
                Return CType(Me("eMailTo"),String)
            End Get
            Set
                Me("eMailTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\Books\")>  _
        Public Property PrEBookDir() As String
            Get
                Return CType(Me("PrEBookDir"),String)
            End Get
            Set
                Me("PrEBookDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\Charts\")>  _
        Public Property PrEChartDir() As String
            Get
                Return CType(Me("PrEChartDir"),String)
            End Get
            Set
                Me("PrEChartDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\Hymnbooks\")>  _
        Public Property PrEHymnBookDir() As String
            Get
                Return CType(Me("PrEHymnBookDir"),String)
            End Get
            Set
                Me("PrEHymnBookDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\leaflet\")>  _
        Public Property PrELeafletDir() As String
            Get
                Return CType(Me("PrELeafletDir"),String)
            End Get
            Set
                Me("PrELeafletDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\Pamphlets\")>  _
        Public Property PrEPamphletDir() As String
            Get
                Return CType(Me("PrEPamphletDir"),String)
            End Get
            Set
                Me("PrEPamphletDir") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Print & Ebook Projects\Periodicals\")>  _
        Public Property PrEPeriodicals() As String
            Get
                Return CType(Me("PrEPeriodicals"),String)
            End Get
            Set
                Me("PrEPeriodicals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("bis;eg;ml;tc")>  _
        Public Property periodicals() As String
            Get
                Return CType(Me("periodicals"),String)
            End Get
            Set
                Me("periodicals") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Print & Ebook Projects\Books\;\\btp-fs\Shared\Print & Ebook Proje"& _ 
            "cts\Charts\;\\btp-fs\Shared\Print & Ebook Projects\Hymnbooks\;\\btp-fs\Shared\Pr"& _ 
            "int & Ebook Projects\leaflet\;\\btp-fs\Shared\Print & Ebook Projects\Pamphlets\;"& _ 
            "\\btp-fs\shared\Print & Ebook Projects\Periodicals\")>  _
        Public Property PrESearchLoc() As String
            Get
                Return CType(Me("PrESearchLoc"),String)
            End Get
            Set
                Me("PrESearchLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.0122 Cost per Sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_20lbPaper() As String
            Get
                Return CType(Me("Cost_20lbPaper"),String)
            End Get
            Set
                Me("Cost_20lbPaper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.01635 Cost per sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_24lbPaper() As String
            Get
                Return CType(Me("Cost_24lbPaper"),String)
            End Get
            Set
                Me("Cost_24lbPaper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".06 Cost per Sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_PamCov() As String
            Get
                Return CType(Me("Cost_PamCov"),String)
            End Get
            Set
                Me("Cost_PamCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.076 Cost per sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_BookCov() As String
            Get
                Return CType(Me("Cost_BookCov"),String)
            End Get
            Set
                Me("Cost_BookCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.03122 Cost per sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_TCCov() As String
            Get
                Return CType(Me("Cost_TCCov"),String)
            End Get
            Set
                Me("Cost_TCCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.124255 Cost per 18 inches per roll. Note: Please leave number at the beginning!"& _ 
            " 10-13-2014")>  _
        Public Property Cost_Laminate() As String
            Get
                Return CType(Me("Cost_Laminate"),String)
            End Get
            Set
                Me("Cost_Laminate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".05 Cost per side / click. Note: Please leave number at the beginning! 10-13-2014"& _ 
            "")>  _
        Public Property Cost_ColorClick() As String
            Get
                Return CType(Me("Cost_ColorClick"),String)
            End Get
            Set
                Me("Cost_ColorClick") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".0048 Cost per side / click. Note: Please leave number at the beginning! 10-13-20"& _ 
            "14")>  _
        Public Property Cost_BlackClick() As String
            Get
                Return CType(Me("Cost_BlackClick"),String)
            End Get
            Set
                Me("Cost_BlackClick") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute(".006 Cost per sheet. Note: Please leave number at the beginning! 10-13-2014")>  _
        Public Property Cost_8_5x11_20lbPaper() As String
            Get
                Return CType(Me("Cost_8_5x11_20lbPaper"),String)
            End Get
            Set
                Me("Cost_8_5x11_20lbPaper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Cost_12x18_20lb() As String
            Get
                Return CType(Me("Cost_12x18_20lb"),String)
            End Get
            Set
                Me("Cost_12x18_20lb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Cost_12x18_24lb() As String
            Get
                Return CType(Me("Cost_12x18_24lb"),String)
            End Get
            Set
                Me("Cost_12x18_24lb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-uv\UV\BTP\MX.ORDERS\")>  _
        Public Property dirMxOrders() As String
            Get
                Return CType(Me("dirMxOrders"),String)
            End Get
            Set
                Me("dirMxOrders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-uv\UV\BTP\MX.XML\")>  _
        Public Property dirMxXML() As String
            Get
                Return CType(Me("dirMxXML"),String)
            End Get
            Set
                Me("dirMxXML") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-uv\UV\BTP\MX.CUSTOM\CustomOrders.xml")>  _
        Public Property MxCustomPath() As String
            Get
                Return CType(Me("MxCustomPath"),String)
            End Get
            Set
                Me("MxCustomPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Pageup\Personalize\GospelOfPeace\Composed\")>  _
        Public Property dir8101IDs() As String
            Get
                Return CType(Me("dir8101IDs"),String)
            End Get
            Set
                Me("dir8101IDs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Tracts\CTC\Composed Imprints\")>  _
        Public Property dir6120IDs() As String
            Get
                Return CType(Me("dir6120IDs"),String)
            End Get
            Set
                Me("dir6120IDs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Calendars\MJNC\Composed Imprints\")>  _
        Public Property dir6880IDs() As String
            Get
                Return CType(Me("dir6880IDs"),String)
            End Get
            Set
                Me("dir6880IDs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Calendars\CPC\Composed Imprints\")>  _
        Public Property dir7427IDs() As String
            Get
                Return CType(Me("dir7427IDs"),String)
            End Get
            Set
                Me("dir7427IDs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ImpositionConfig.xml")>  _
        Public Property PcConfigPath() As String
            Get
                Return CType(Me("PcConfigPath"),String)
            End Get
            Set
                Me("PcConfigPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Books\Imposition\12x18 2UP Book Cover Layout.indd")>  _
        Public Property bkCovImposeTemplatePath() As String
            Get
                Return CType(Me("bkCovImposeTemplatePath"),String)
            End Get
            Set
                Me("bkCovImposeTemplatePath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Books\Covers\4up 12x18 - Gift")>  _
        Public Property dirMiniGiftBkCov() As String
            Get
                Return CType(Me("dirMiniGiftBkCov"),String)
            End Get
            Set
                Me("dirMiniGiftBkCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Books\Bodies\8up Full Bleed - MiniBook Gift\")>  _
        Public Property dirMiniGiftBkBod() As String
            Get
                Return CType(Me("dirMiniGiftBkBod"),String)
            End Get
            Set
                Me("dirMiniGiftBkBod") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Calendars\CPC\Users\")>  _
        Public Property dir7427Users() As String
            Get
                Return CType(Me("dir7427Users"),String)
            End Get
            Set
                Me("dir7427Users") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Calendars\MJNC\Users\")>  _
        Public Property dir6880Users() As String
            Get
                Return CType(Me("dir6880Users"),String)
            End Get
            Set
                Me("dir6880Users") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Tracts\CTC\Users\")>  _
        Public Property dir6120Users() As String
            Get
                Return CType(Me("dir6120Users"),String)
            End Get
            Set
                Me("dir6120Users") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Pageup\Personalize\GospelOfPeace\Users")>  _
        Public Property dir8101Users() As String
            Get
                Return CType(Me("dir8101Users"),String)
            End Get
            Set
                Me("dir8101Users") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Print & Ebook Projects\ShareWord\")>  _
        Public Property dirShareWordProjects() As String
            Get
                Return CType(Me("dirShareWordProjects"),String)
            End Get
            Set
                Me("dirShareWordProjects") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\ShareWord\")>  _
        Public Property dirShareWordProduction() As String
            Get
                Return CType(Me("dirShareWordProduction"),String)
            End Get
            Set
                Me("dirShareWordProduction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\pc-john\ShareWord\")>  _
        Public Property dirShareWordJohnK() As String
            Get
                Return CType(Me("dirShareWordJohnK"),String)
            End Get
            Set
                Me("dirShareWordJohnK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\Shared\Production\Custom Books")>  _
        Public Property dir42194IDs() As String
            Get
                Return CType(Me("dir42194IDs"),String)
            End Get
            Set
                Me("dir42194IDs") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\pc-john\Documents")>  _
        Public Property dirShareWordJohnDocuments() As String
            Get
                Return CType(Me("dirShareWordJohnDocuments"),String)
            End Get
            Set
                Me("dirShareWordJohnDocuments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Computer\Macros-Actions-Presets-Droplets\Indesign\Scripts\")>  _
        Public Property dirInddScripts() As String
            Get
                Return CType(Me("dirInddScripts"),String)
            End Get
            Set
                Me("dirInddScripts") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Web\Products\2 New and Updated Pics\")>  _
        Public Property dirHomePrintExportLoc() As String
            Get
                Return CType(Me("dirHomePrintExportLoc"),String)
            End Get
            Set
                Me("dirHomePrintExportLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("cbuchanan@bibletruthpublishers.com;dmacy@bibletruthpublishers.com")>  _
        Public Property eMailProofReportTo() As String
            Get
                Return CType(Me("eMailProofReportTo"),String)
            End Get
            Set
                Me("eMailProofReportTo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\btp-fs\shared\Production\Alignment Sheets\")>  _
        Public Property dirAlignmentSheet() As String
            Get
                Return CType(Me("dirAlignmentSheet"),String)
            End Get
            Set
                Me("dirAlignmentSheet") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SqlServer() As String
            Get
                Return CType(Me("SqlServer"),String)
            End Get
            Set
                Me("SqlServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("BTP_80_Products")>  _
        Public Property SqlProductsDatabase() As String
            Get
                Return CType(Me("SqlProductsDatabase"),String)
            End Get
            Set
                Me("SqlProductsDatabase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SqlUser() As String
            Get
                Return CType(Me("SqlUser"),String)
            End Get
            Set
                Me("SqlUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SqlPassword() As String
            Get
                Return CType(Me("SqlPassword"),String)
            End Get
            Set
                Me("SqlPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CB_Job_Q")>  _
        Public Property SqlLineupDatabase() As String
            Get
                Return CType(Me("SqlLineupDatabase"),String)
            End Get
            Set
                Me("SqlLineupDatabase") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("X:\Production\Periodicals\")>  _
        Public Property dirPeriodicals() As String
            Get
                Return CType(Me("dirPeriodicals"),String)
            End Get
            Set
                Me("dirPeriodicals") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.LineUp.My.MySettings
            Get
                Return Global.LineUp.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
